name: feature_browse
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  # library
  safe_bloc:
    path: ../../library/safe_bloc
  service_locator:
    path: ../../library/service_locator
  manga_service_firebase:
    path: ../../library/manga_service_firebase

  # entity
  entity_manga:
    path: ../../entity/entity_manga

  # domain
  domain_manga:
    path: ../../domain/domain_manga

  # core
  core_route:
    path: ../../core/core_route
  core_network:
    path: ../../core/core_network
  core_environment:
    path: ../../core/core_environment
  core_auth:
    path: ../../core/core_auth

  # ui
  ui_common:
    path: ../../ui/ui_common
  ui_browse:
    path: ../../ui/ui_browse

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
