name: manga_dex_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  dio: ^5.7.0
  equatable: ^2.0.5
  retrofit: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.2.1
