name: ui_browse
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.16.0
  rxdart: ^0.27.7

  # domain
  domain_manga:
    path: ../../domain/domain_manga

  # entity
  entity_manga:
    path: ../../entity/entity_manga

  # library
  service_locator:
    path: ../../library/service_locator
  safe_bloc:
    path: ../../library/safe_bloc
  manga_dex_api:
    path: ../../library/manga_dex_api
  log_box:
    git:
      url: https://github.com/robzimpulse/log_box.git
      ref: master
      path: packages/log_box
  log_box_in_app_webview_logger:
    git:
      url: https://github.com/robzimpulse/log_box.git
      ref: master
      path: packages/log_box_in_app_webview_logger

  # core
  core_environment:
    path: ../../core/core_environment
  core_route:
    path: ../../core/core_route
  core_network:
    path: ../../core/core_network
  core_storage:
    path: ../../core/core_storage

  #ui
  ui_common:
    path: ../../ui/ui_common

  # feature
  feature_common:
    path: ../../feature/feature_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
