name: mangastash

packages:
  - module/**
  - '*'

ide:
  intellij:
    enabled: false

scripts:
  flutter_clean:
    description: Clean all packages.
    run: melos exec -c 1 -- "flutter clean"
  get:
    description: Get dependencies for all packages.
    run: melos exec -- "flutter pub get"
  generate:
    description: Generate files for all packages.
    run: melos exec --depends-on=build_runner -- "flutter pub run build_runner build --delete-conflicting-outputs;"
  upgrade:
    description: Upgrade dependencies for all packages.
    run: melos exec -- "flutter pub upgrade"
  unit_test:
    run: melos exec -c 3 --flutter --fail-fast -- flutter test --no-pub