name: mangastash

packages:
  - module/**
  - '*'

ide:
  intellij:
    enabled: false

scripts:
  get:
    description: Get dependencies for all packages.
    run: |
      melos exec -- "flutter pub get"
  generate:
      run: melos exec --depends-on=build_runner -- "flutter pub run build_runner build --delete-conflicting-outputs;"
      description: Generate files for all packages.