name: mangastash

packages:
  - module/**
  - '*'

ide:
  intellij:
    enabled: false

scripts:
  flutter_clean:
    description: Clean all packages.
    run: flutter clean
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  get:
    description: Get dependencies for all packages.
    run: flutter pub get
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  generate:
    description: Generate files for all packages.
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"

  upgrade:
    description: Upgrade dependencies for all packages.
    run: flutter pub upgrade
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  test:
    description: Test for all packages.
    run: flutter test
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true
    packageFilters:
      dirExists: "test"