name: mangastash
description: Manga Reader Apps
publish_to: 'none'

version: 0.1.1+0

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  responsive_framework: ^1.0.0
  ios_willpop_transition_theme: ^0.0.6
  flex_color_scheme: ^7.3.1
  rxdart: ^0.27.7
  universal_io: ^2.2.2

  # library
  safe_bloc:
    path: module/library/safe_bloc
  service_locator:
    path: module/library/service_locator
  log_box:
    path: module/library/log_box
  manga_service_firebase:
    path: module/library/manga_service_firebase
  manga_service_drift:
    path: module/library/manga_service_drift

  # core
  core_environment:
    path: module/core/core_environment
  core_network:
    path: module/core/core_network
  core_route:
    path: module/core/core_route
  core_storage:
    path: module/core/core_storage

  # domain
  domain_manga:
    path: module/domain/domain_manga

  # ui
  ui_common:
    path: module/ui/ui_common

  # feature
  feature_browse:
    path: module/feature/feature_browse
  feature_history:
    path: module/feature/feature_history
  feature_library:
    path: module/feature/feature_library
  feature_more:
    path: module/feature/feature_more
  feature_updates:
    path: module/feature/feature_updates
  feature_common:
    path: module/feature/feature_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

