name: log_box
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  rxdart: ^0.27.7
  uuid: ^4.5.1
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0