multitenancy_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers: # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        grpc: # on port 4317
          endpoint: "tempo:4317"
        http: # on port 4318
          endpoint: "tempo:4318"
          traces_url_path: "/otlp/v1/traces"

ingester:
  trace_idle_period: '10s' # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 1_000_000 # cut the head block when it hits this size or ...
  max_block_duration: '5m' #   this much time passes

compactor:
  compaction:
    compaction_window: '1h' # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000 # maximum size of compacted blocks
    block_retention: '24h'
    compacted_block_retention: '10m'

metrics_generator:
  registry:
    external_labels:
      source: 'tempo'
      cluster: '@grafana/faro-demo'
  storage:
    path: '/tmp/tempo/generator/wal'
    remote_write:
      - url: 'http://mimir:9009/api/v1/push'
        send_exemplars: true
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true

storage:
  trace:
    backend: 'local' # backend configuration to use
    block:
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      v2_index_downsample_bytes: 1000 # number of bytes per index record
      v2_encoding: 'zstd' # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    wal:
      path: '/tmp/tempo/wal' # where to store the the wal locally
      v2_encoding: 'snappy' # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: '/tmp/tempo/blocks'
    pool:
      max_workers: 100 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000

overrides:
  metrics_generator_processors:
    - 'service-graphs'
    - 'span-metrics'
    - 'local-blocks'
