{
 "title": "Apps Performance Dashboard",
 "description": "Apps Metric Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{kind=\"measurement\"} |= `value_cpu_usage`"
    }
   ]
  },
  {
   "title": "Average Apps Refresh Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{kind=\"measurement\"} |= `type=app_refresh_rate`"
    }
   ]
  },
  {
   "title": "Average Apps Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{kind=\"measurement\"} |= `type=app_memory`"
    }
   ]
  }
 ]
}