name: feature_more
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  # library
  safe_bloc:
    path: ../../library/safe_bloc
  service_locator:
    path: ../../library/service_locator

  # core
  core_route:
    path: ../../core/core_route
  core_auth:
    path: ../../core/core_auth
  core_environment:
    path: ../../core/core_environment

  # ui
  ui_more:
    path: ../../ui/ui_more
  ui_common:
    path: ../../ui/ui_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
