// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZeUa8SbXSkPsYkLFTuAMiXKQTBAebk4',
    appId: '1:333417519386:web:2571a02007b5ecf02474a3',
    messagingSenderId: '333417519386',
    projectId: 'mangastash-4bf38',
    authDomain: 'mangastash-4bf38.firebaseapp.com',
    storageBucket: 'mangastash-4bf38.appspot.com',
    measurementId: 'G-ZL4LVH17MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaI12EqaLbpdpS3HfzodBTe5EGG9BwQFg',
    appId: '1:333417519386:android:9217a7a207bde7a22474a3',
    messagingSenderId: '333417519386',
    projectId: 'mangastash-4bf38',
    storageBucket: 'mangastash-4bf38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONMNBT5s2XmXWFufjxvrtaZ9MHbOYz3Q',
    appId: '1:333417519386:ios:3325359d515cc8872474a3',
    messagingSenderId: '333417519386',
    projectId: 'mangastash-4bf38',
    storageBucket: 'mangastash-4bf38.appspot.com',
    iosBundleId: 'com.robzimpulse.mangastash.mangastash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONMNBT5s2XmXWFufjxvrtaZ9MHbOYz3Q',
    appId: '1:333417519386:ios:3325359d515cc8872474a3',
    messagingSenderId: '333417519386',
    projectId: 'mangastash-4bf38',
    storageBucket: 'mangastash-4bf38.appspot.com',
    iosBundleId: 'com.robzimpulse.mangastash.mangastash',
  );
}
