name: dio_inspector
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  collection: ^1.16.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0