name: entity_manga
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.16.0
  json_annotation: ^4.9.0

  # core
  core_environment:
    path: ../../core/core_environment

  # library
  manga_dex_api:
    path: ../../library/manga_dex_api
  manga_service_firebase:
    path: ../../library/manga_service_firebase
  manga_service_drift:
    path: ../../library/manga_service_drift
  text_similarity:
    path: ../../library/text_similarity

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
