name: feature_common
description: "A new Flutter project."
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  # library
  service_locator:
    path: ../../library/service_locator

  # core
  core_route:
    path: ../../core/core_route
  core_network:
    path: ../../core/core_network
  core_environment:
    path: ../../core/core_environment

  # ui
  ui_common:
    path: ../../ui/ui_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0