name: ui_more
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.16.0

  # library
  service_locator:
    path: ../../library/service_locator
  safe_bloc:
    path: ../../library/safe_bloc

  # core
  core_environment:
    path: ../../core/core_environment
  core_route:
    path: ../../core/core_route
  core_network:
    path: ../../core/core_network

  #ui
  ui_common:
    path: ../../ui/ui_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
