name: feature_history
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  # library
  safe_bloc:
    path: ../../library/safe_bloc
  service_locator:
    path: ../../library/service_locator

  # core
  core_route:
    path: ../../core/core_route

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
