name: core_auth
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.20.0
  focus_detector_v2: ^3.1.0+1

  # library
  service_locator:
    path: ../../library/service_locator
  safe_bloc:
    path: ../../library/safe_bloc
  log_box:
    path: ../../library/log_box

  # core
  core_storage:
    path: ../../core/core_storage
  core_route:
    path: ../../core/core_route

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
