targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            database: lib/src/database/database.dart
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5