name: Build Application on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: web
            os: ubuntu-latest
            path: /build/web
          - platform: macos
            os: macos-latest
            path: build/macos/Build/Products/Release/mangastash.app
          - platform: windows
            os: windows-latest
            path: build/windows/x64/runner/Release/mangastash.exe
          - platform: linux
            os: ubuntu-latest
            path: build/linux/x64/release/bundle/mangastash
#          - platform: ipa
#            os: macos-latest
#            path: build/ios/ipa
          - platform: apk
            os: ubuntu-latest
            path: build/app/outputs/apk/release/app-release.apk
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: 'Install Linux Dependencies'
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: 'Install Java'
        uses: actions/setup-java@v2
        if: ${{ matrix.platform == 'apk' }}
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - name: 'Install Melos'
        run: flutter pub global activate melos 6.2.0
      - name: 'Bootstrap Workspace'
        run: melos bootstrap --verbose
      - name: 'Build Application'
        run: flutter build ${{ matrix.platform }}
      - name: 'Save Artifact'
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: ${{ matrix.path }}
