name: Build Application on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: web
            os: ubuntu-latest
            path: build/web
          - platform: macos
            os: macos-15
            path: build/macos/Build/Products/Release/mangastash.app
          - platform: windows
            os: windows-latest
            path: build/windows/x64/runner/Release/mangastash.exe
          - platform: linux
            os: ubuntu-latest
            path: build/linux/x64/release/bundle/mangastash
#          - platform: ipa
#            os: macos-latest
#            path: build/ios/ipa
          - platform: apk
            os: ubuntu-latest
            path: build/app/outputs/apk/release/app-release.apk
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: 'Install Linux Dependencies'
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: 'Install Java'
        uses: actions/setup-java@v2
        if: ${{ matrix.platform == 'apk' }}
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - name: 'Install Melos'
        run: flutter pub global activate melos 6.2.0
      - name: 'Bootstrap Workspace'
        run: melos bootstrap --verbose
      - name: 'Build Application'
        run: flutter build ${{ matrix.platform }}
      - name: 'Compress Directory'
        uses: somaz94/compress-decompress@v1
        if: ${{ matrix.platform == 'web' }}
        with:
          command: compress
          source: ${{ matrix.path }}
          format: zip
          dest: build
          destfilename: 'web'
      - name: 'Save Artifact Non Web'
        if: ${{ matrix.platform != 'web' }}
        id: upload_artifact_non_web
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: ${{ matrix.path }}
      - name: 'Save Artifact Web'
        if: ${{ matrix.platform == 'web' }}
        id: upload_artifact_web
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: ${{ matrix.path }}.zip

  post-build:
    needs: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: 'Download All Artifacts'
        uses: actions/download-artifact@v5
        with:
          path: release/
          pattern: release-*
          merge-multiple: true
      - name: 'Find Comment'
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: 'Create or Update Comment'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            body: |-
            ![badge]
            
            Build Successful! You can find a link to the downloadable artifact below.
            
            | Platform     | Link                    |
            | -------- | ----------------------- |
            | Android   | -     |
            | iOS     | -     |
            | Web     | -     |
            | Windows | - |
            | Macos | - |
            | Linux | - |
            
            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==
          
