name: Build Web

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: "Install Melos"
        run: flutter pub global activate melos 2.9.0

      - name: "Bootstrap Workspace"
        run: melos bootstrap --verbose

      - name: "Install Dependency"
        run: melos get --verbose

      - name: "Build Flutter Web"
        run: flutter build web --base-href "/mangastash/"

      - name: "Deploy to Github Page"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
