name: Build APK

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          cache: true

      - name: "Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Install Melos"
        run: flutter pub global activate melos 6.2.0

      - name: "Bootstrap Workspace"
        run: melos bootstrap --verbose

      - name: "Install Dependency"
        run: melos get --verbose

      - name: "Build Application"
        run: flutter build apk

      - name: 'Save Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/app/outputs/apk/release/app-release.apk

      - name: Send debug APK to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Here is the debug APK for ${{ github.event_name }}
            Runner OS: ${{ runner.os }}
            Event: ${{ github.event_name }}
            Job ID: ${{ github.job }}
            Triggered by: ${{ github.actor }}
            Branch or TAG: ${{ github.ref }}
            Base ref: ${{ github.base_ref }}
            Head ref: ${{ github.head_ref }}
            Commit SHA: ${{ github.sha }}
          document: build/app/outputs/apk/release/app-release.apk
