name: Build APK

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on: [push, workflow_dispatch]

jobs:
  setup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          cache: true

      - name: "Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Install Melos"
        run: flutter pub global activate melos 6.2.0

      - name: "Bootstrap Workspace"
        run: melos bootstrap --verbose

      - name: "Install Dependency"
        run: melos get --verbose

  build-apk:
    needs: setup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "Build Application"
        run: flutter build apk

  post-build-apk:
    needs: build-apk
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: 'Save Artifact'
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/app/outputs/apk/release/app-release.apk

      - name: Send debug APK to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Here is the debug APK for ${{ github.event_name }}
            Runner OS: ${{ runner.os }}
            Event: ${{ github.event_name }}
            Job ID: ${{ github.job }}
            Triggered by: ${{ github.actor }}
            Branch or TAG: ${{ github.ref }}
            Commit SHA: ${{ github.sha }}
            Artifact URL is: ${{ steps.upload_artifact.outputs.artifact-url }}

  build-web:
    needs: setup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "Build Application"
        run: flutter build web

  post-build-web:
    needs: build-web
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MANGASTASH_4BF38 }}
          channelId: live
          projectId: mangastash-4bf38

      - name: "Deploy to Github Page"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'robzimpulse'
          user_email: 'kugelfang.killaruna@gmail.com'
          commit_message: 'Publish to gh-pages'

      - name: 'Save Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/web
