name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true

      - name: "Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Install Melos"
        run: flutter pub global activate melos 6.2.0

      - name: "Bootstrap Workspace"
        run: melos bootstrap --verbose

      - name: "Build Application"
        run: flutter build apk

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/app/outputs/apk/release/app-release.apk