name: feature_auth
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0

  # library
  safe_bloc:
    path: ../../library/safe_bloc
  service_locator:
    path: ../../library/service_locator

  # core
  core_route:
    path: ../../core/core_route
  core_network:
    path: ../../core/core_network
  core_auth:
    path: ../../core/core_auth

  # ui
  ui_common:
    path: ../../ui/ui_common
  ui_auth:
    path: ../../ui/ui_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
